[package]
name = "geoforge_v2"
description = "GeoForge V2 CLI — procedural world generation"
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[[bin]]
name = "geoforge_v2"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
geoforge-cosmology = { path = "../../libs/geoforge-cosmology" }
geoforge-types = { path = "../../libs/geoforge-types" }
